In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
inventory_df=pd.read_csv("/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Cleaned/Inventory_Cleaned.csv")

In [ ]:
sales_df=pd.read_csv("/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Cleaned/Sales_Cleaned.csv")

In [ ]:
inventory_df.head()

,order-now,product id,product name,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
0,green,19,Nike Men's Fingertrap Max Training Shoe,10,1,69,30,1,1,35,25
1,orange,24,Elevation Training Mask 2.0,10,3,175,30,5,0,175,144
2,green,35,adidas Brazuca 2014 Official Match Ball,10,1,65,30,1,1,35,25
3,green,37,adidas Kids' F5 Messi FG Soccer Cleat,10,3,328,30,5,1,175,146
4,orange,44,adidas Men's F10 Messi TRX FG Soccer Cleat,10,3,175,30,5,0,175,145

In [ ]:
sales_df.head()

,product_id,product_name,category_name,department_name,order_id,order_date,shipping_date,delivery_status,shipping_mode,order_region,...,market,order_quantity,product_price,sales,benefit_per_order,order_profit,scheduled_shipping_days,actual_shipping_days,order_status,customer_segment
0,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,53963,2/26/2017 17:17,03-02-2017 17:17,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,9.610000,9.610000,2,4,Pending Payment,Corporate
1,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,3908,2/27/2015 0:47,03-03-2015 00:47,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,9.490000,9.490000,2,4,Pending Payment,Corporate
2,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,52009,1/29/2017 4:43,02-03-2017 04:43,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,30.709999,30.709999,2,5,Payment Review,Corporate
3,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,1179,1/18/2015 4:42,1/23/2015 4:42,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,27.549999,27.549999,2,5,Pending Payment,Corporate
4,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,56019,3/28/2017 17:36,04-02-2017 17:36,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,47.500000,47.500000,2,5,Pending Payment,Corporate

In [ ]:
inventory_df.columns

Index(['order-now', 'product id', 'product name', 'avg lead time',
       'avg order qty', 'current stock', 'max lead time', 'max order qty',
       'mod', 'reorder point', 'safety stock'],
      dtype='object')

In [ ]:
sales_df.columns

Index(['product_id', 'product_name', 'category_name', 'department_name',
       'order_id', 'order_date', 'shipping_date', 'delivery_status',
       'shipping_mode', 'order_region', 'order_country', 'market',
       'order_quantity', 'product_price', 'sales', 'benefit_per_order',
       'order_profit', 'scheduled_shipping_days', 'actual_shipping_days',
       'order_status', 'customer_segment'],
      dtype='object')

In [ ]:
inventory_df["product id"].dtype

dtype('int64')

In [ ]:
sales_df["product_id"].dtype

dtype('int64')

In [ ]:
inventory_df["product id"].isin(sales_df["product_id"]).sum()

np.int64(118)

In [ ]:
sales_df["product_id"].isin(inventory_df["product id"]).sum()

np.int64(180519)

In [ ]:
final_df = pd.merge(
    sales_df,
    inventory_df,
    on="product_id",
    how="left"
)

In [ ]:
inventory_df.rename(columns={"product id": "product_id"}, inplace=True)

In [ ]:
final_df.shape

(180519, 31)

In [ ]:
final_df.info

<bound method DataFrame.info of         product_id                          product_name     category_name  \
0              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
1              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
2              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
3              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
4              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
...            ...                                   ...               ...
180514         365      Perfect Fitness Perfect Rip Deck            Cleats
180515         365      Perfect Fitness Perfect Rip Deck            Cleats
180516         191     Nike Men's Free 5.0+ Running Shoe  Cardio Equipment
180517         365      Perfect Fitness Perfect Rip Deck            Cleats
180518         365      Perfect Fitness Perfect Rip Deck            Cleats

       department_name  order_id        order_date     shipping_date  \
0                 Golf     53963   2/26/2017 17:17  03-02-2017 17:17
1                 Golf      3908    2/27/2015 0:47  03-03-2015 00:47
2                 Golf     52009    1/29/2017 4:43  02-03-2017 04:43
3                 Golf      1179    1/18/2015 4:42    1/23/2015 4:42
4                 Golf     56019   3/28/2017 17:36  04-02-2017 17:36
...                ...       ...               ...               ...
180514         Apparel     49890   12/29/2016 6:20  01-04-2017 06:20
180515         Apparel     29410  03-05-2016 07:16  03-11-2016 07:16
180516        Footwear     24350  12/22/2015 10:32  12/28/2015 10:32
180517         Apparel     45725  10/29/2016 11:09  11-04-2016 11:09
180518         Apparel     24050   12/18/2015 1:26   12/24/2015 1:26

       delivery_status   shipping_mode     order_region  ... order-now  \
0                 Late    Second Class  Central America  ...    orange
1                 Late    Second Class  Central America  ...    orange
2                 Late    Second Class  Central America  ...    orange
3                 Late    Second Class  Central America  ...    orange
4                 Late    Second Class  Central America  ...    orange
...                ...             ...              ...  ...       ...
180514            Late  Standard Class        West Asia  ...     green
180515            Late  Standard Class     Eastern Asia  ...     green
180516            Late  Standard Class   Southeast Asia  ...     green
180517            Late  Standard Class        West Asia  ...     green
180518            Late  Standard Class     Eastern Asia  ...     green

                                product name  avg lead time  avg order qty  \
0       Nike Men's Dri-FIT Victory Golf Polo             10              3
1       Nike Men's Dri-FIT Victory Golf Polo             10              3
2       Nike Men's Dri-FIT Victory Golf Polo             10              3
3       Nike Men's Dri-FIT Victory Golf Polo             10              3
4       Nike Men's Dri-FIT Victory Golf Polo             10              3
...                                      ...            ...            ...
180514      Perfect Fitness Perfect Rip Deck             10              3
180515      Perfect Fitness Perfect Rip Deck             10              3
180516     Nike Men's Free 5.0+ Running Shoe             10              3
180517      Perfect Fitness Perfect Rip Deck             10              3
180518      Perfect Fitness Perfect Rip Deck             10              3

        current stock  max lead time  max order qty  mod  reorder point  \
0                 175             30              5    0            175
1                 175             30              5    0            175
2                 175             30              5    0            175
3                 175             30              5    0            175
4                 175             30              5    0            175
...               ...            ...            ...  ...            ...
180514            325             30              5    1            175
180515            325             30              5    1            175
180516            321             30              5    1            175
180517            325             30              5    1            175
180518            325             30              5    1            175

       safety stock
0               146
1               146
2               146
3               146
4               146
...             ...
180514          145
180515          145
180516          145
180517          145
180518          145

[180519 rows x 31 columns]>

In [ ]:
final_df.head(1)

,product_id,product_name,category_name,department_name,order_id,order_date,shipping_date,delivery_status,shipping_mode,order_region,...,order-now,product name,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
0,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,53963,2/26/2017 17:17,03-02-2017 17:17,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146

In [ ]:
final_df.isnull().sum()

product_id                 0
product_name               0
category_name              0
department_name            0
order_id                   0
order_date                 0
shipping_date              0
delivery_status            0
shipping_mode              0
order_region               0
order_country              0
market                     0
order_quantity             0
product_price              0
sales                      0
benefit_per_order          0
order_profit               0
scheduled_shipping_days    0
actual_shipping_days       0
order_status               0
customer_segment           0
order-now                  0
product name               0
avg lead time              0
avg order qty              0
current stock              0
max lead time              0
max order qty              0
mod                        0
reorder point              0
safety stock               0
dtype: int64

In [ ]:
final_df.to_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Processed/Final_Inventory_Model.csv",
    index=False
)

In [ ]:
final_