In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
final_df=pd.read_csv("")

In [ ]:
final_df = pd.read_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Processed/Final_Inventory_Model.csv"
)

In [ ]:
final_df.shape

(180519, 31)

In [ ]:
final_df.info

<bound method DataFrame.info of         product_id                          product_name     category_name  \
0              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
1              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
2              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
3              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
4              502  Nike Men's Dri-FIT Victory Golf Polo   Women's Apparel
...            ...                                   ...               ...
180514         365      Perfect Fitness Perfect Rip Deck            Cleats
180515         365      Perfect Fitness Perfect Rip Deck            Cleats
180516         191     Nike Men's Free 5.0+ Running Shoe  Cardio Equipment
180517         365      Perfect Fitness Perfect Rip Deck            Cleats
180518         365      Perfect Fitness Perfect Rip Deck            Cleats

       department_name  order_id        order_date     shipping_date  \
0                 Golf     53963   2/26/2017 17:17  03-02-2017 17:17
1                 Golf      3908    2/27/2015 0:47  03-03-2015 00:47
2                 Golf     52009    1/29/2017 4:43  02-03-2017 04:43
3                 Golf      1179    1/18/2015 4:42    1/23/2015 4:42
4                 Golf     56019   3/28/2017 17:36  04-02-2017 17:36
...                ...       ...               ...               ...
180514         Apparel     49890   12/29/2016 6:20  01-04-2017 06:20
180515         Apparel     29410  03-05-2016 07:16  03-11-2016 07:16
180516        Footwear     24350  12/22/2015 10:32  12/28/2015 10:32
180517         Apparel     45725  10/29/2016 11:09  11-04-2016 11:09
180518         Apparel     24050   12/18/2015 1:26   12/24/2015 1:26

       delivery_status   shipping_mode     order_region  ... order-now  \
0                 Late    Second Class  Central America  ...    orange
1                 Late    Second Class  Central America  ...    orange
2                 Late    Second Class  Central America  ...    orange
3                 Late    Second Class  Central America  ...    orange
4                 Late    Second Class  Central America  ...    orange
...                ...             ...              ...  ...       ...
180514            Late  Standard Class        West Asia  ...     green
180515            Late  Standard Class     Eastern Asia  ...     green
180516            Late  Standard Class   Southeast Asia  ...     green
180517            Late  Standard Class        West Asia  ...     green
180518            Late  Standard Class     Eastern Asia  ...     green

                                product name  avg lead time  avg order qty  \
0       Nike Men's Dri-FIT Victory Golf Polo             10              3
1       Nike Men's Dri-FIT Victory Golf Polo             10              3
2       Nike Men's Dri-FIT Victory Golf Polo             10              3
3       Nike Men's Dri-FIT Victory Golf Polo             10              3
4       Nike Men's Dri-FIT Victory Golf Polo             10              3
...                                      ...            ...            ...
180514      Perfect Fitness Perfect Rip Deck             10              3
180515      Perfect Fitness Perfect Rip Deck             10              3
180516     Nike Men's Free 5.0+ Running Shoe             10              3
180517      Perfect Fitness Perfect Rip Deck             10              3
180518      Perfect Fitness Perfect Rip Deck             10              3

        current stock  max lead time  max order qty  mod  reorder point  \
0                 175             30              5    0            175
1                 175             30              5    0            175
2                 175             30              5    0            175
3                 175             30              5    0            175
4                 175             30              5    0            175
...               ...            ...            ...  ...            ...
180514            325             30              5    1            175
180515            325             30              5    1            175
180516            321             30              5    1            175
180517            325             30              5    1            175
180518            325             30              5    1            175

       safety stock
0               146
1               146
2               146
3               146
4               146
...             ...
180514          145
180515          145
180516          145
180517          145
180518          145

[180519 rows x 31 columns]>

In [ ]:
final_df.describe()

,product_id,order_id,order_quantity,product_price,sales,benefit_per_order,order_profit,scheduled_shipping_days,actual_shipping_days,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.0,180519.000000,180519.000000,180519.0,180519.000000,180519.000000,180519.000000,180519.000000
mean,692.509764,36221.894903,2.127638,141.232550,203.772096,21.974989,21.974989,2.931847,3.497654,10.0,2.127970,168.282159,30.0,3.255940,0.615414,113.957894,93.003279
std,336.446807,21045.379569,1.453451,139.732492,132.273077,104.433526,104.433526,1.374449,1.623722,0.0,0.991781,113.920993,0.0,1.983562,0.486499,69.424656,59.794170
min,19.000000,1.000000,1.000000,9.990000,9.990000,-4274.979980,-4274.979980,0.000000,0.000000,10.0,1.000000,35.000000,30.0,1.000000,0.000000,35.000000,25.000000
25%,403.000000,18057.000000,1.000000,50.000000,119.980003,7.000000,7.000000,2.000000,2.000000,10.0,1.000000,63.000000,30.0,1.000000,0.000000,35.000000,25.000000
50%,627.000000,36140.000000,1.000000,59.990002,199.919998,31.520000,31.520000,4.000000,3.000000,10.0,3.000000,175.000000,30.0,5.000000,1.000000,175.000000,145.000000
75%,1004.000000,54144.000000,3.000000,199.990005,299.950012,64.800003,64.800003,4.000000,5.000000,10.0,3.000000,321.000000,30.0,5.000000,1.000000,175.000000,146.000000
max,1363.000000,77204.000000,5.000000,1999.989990,1999.989990,911.799988,911.799988,4.000000,6.000000,10.0,3.000000,330.000000,30.0,5.000000,1.000000,175.000000,148.000000

In [ ]:
final_df.head()

,product_id,product_name,category_name,department_name,order_id,order_date,shipping_date,delivery_status,shipping_mode,order_region,...,order-now,product name,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
0,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,53963,2/26/2017 17:17,03-02-2017 17:17,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146
1,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,3908,2/27/2015 0:47,03-03-2015 00:47,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146
2,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,52009,1/29/2017 4:43,02-03-2017 04:43,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146
3,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,1179,1/18/2015 4:42,1/23/2015 4:42,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146
4,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,56019,3/28/2017 17:36,04-02-2017 17:36,Late,Second Class,Central America,...,orange,Nike Men's Dri-FIT Victory Golf Polo,10,3,175,30,5,0,175,146

**Feature Engineering**

In [ ]:
final_df["delivery_delay"] = (
    final_df["actual_shipping_days"] -
    final_df["scheduled_shipping_days"]
)

In [ ]:
final_df[["actual_shipping_days",
          "scheduled_shipping_days",
          "delivery_delay"]].head()

   actual_shipping_days  scheduled_shipping_days  delivery_delay
0                     4                        2               2
1                     4                        2               2
2                     5                        2               3
3                     5                        2               3
4                     5                        2               3

In [ ]:
final_df["delivery_status_new"] = final_df["delivery_delay"].apply(
    lambda x: "Delayed" if x > 0 else "On Time"
)

In [ ]:
final_df["delivery_status_new"].value_counts()

delivery_status_new
Delayed    103400
On Time     77119
Name: count, dtype: int64

In [ ]:
final_df["inventory_value"] = (
    final_df["current stock"] *
    final_df["product_price"]
)

In [ ]:
final_df["stock_gap"] = (
    final_df["current stock"] -
    final_df["reorder point"]
)

In [ ]:
final_df["reorder_required"] = final_df.apply(
    lambda row: "Yes"
    if row["current stock"] <= row["reorder point"]
    else "No",
    axis=1
)

In [ ]:
final_df["reorder_required"].value_counts()

reorder_required
No     111094
Yes     69425
Name: count, dtype: int64

In [ ]:
def stock_status(row):
    if row["current stock"] <= row["safety_stock"]:
        return "Critical"

    elif row["current stock"] <= row["reorder point"]:
        return "Low Stock"

    else:
        return "Healthy"

In [ ]:
final_df["stock_status"] = final_df.apply(stock_status, axis=1)

KeyError: 'safety_stock'

In [ ]:
final_df.columns.tolist()

['product_id',
 'product_name',
 'category_name',
 'department_name',
 'order_id',
 'order_date',
 'shipping_date',
 'delivery_status',
 'shipping_mode',
 'order_region',
 'order_country',
 'market',
 'order_quantity',
 'product_price',
 'sales',
 'benefit_per_order',
 'order_profit',
 'scheduled_shipping_days',
 'actual_shipping_days',
 'order_status',
 'customer_segment',
 'order-now',
 'product name',
 'avg lead time',
 'avg order qty',
 'current stock',
 'max lead time',
 'max order qty',
 'mod',
 'reorder point',
 'safety stock',
 'delivery_delay',
 'delivery_status_new',
 'inventory_value',
 'stock_gap',
 'reorder_required',
 'stock_status']

In [ ]:
def stock_status(row):

    if row["current stock"] <= row["safety stock"]:
        return "Critical"

    elif row["current stock"] <= row["reorder point"]:
        return "Low Stock"

    else:
        return "Healthy"

In [ ]:
final_df["stock_status"] = final_df.apply(stock_status, axis=1)

In [ ]:
final_df["stock_status"].value_counts()

stock_status
Healthy      111094
Low Stock     69425
Name: count, dtype: int64

In [ ]:
final_df[[
    "delivery_delay",
    "delivery_status_new",
    "inventory_value",
    "stock_gap",
    "reorder_required",
    "stock_status"
]].head()

,delivery_delay,delivery_status_new,inventory_value,stock_gap,reorder_required,stock_status
0,2,Delayed,8750.0,0,Yes,Low Stock
1,2,Delayed,8750.0,0,Yes,Low Stock
2,3,Delayed,8750.0,0,Yes,Low Stock
3,3,Delayed,8750.0,0,Yes,Low Stock
4,3,Delayed,8750.0,0,Yes,Low Stock

In [ ]:
final_df["delivery_status_new"].value_counts()

delivery_status_new
Delayed    103400
On Time     77119
Name: count, dtype: int64

In [ ]:
final_df["reorder_required"].value_counts()

reorder_required
No     111094
Yes     69425
Name: count, dtype: int64

In [ ]:
final_df["stock_status"].value_counts()

stock_status
Healthy      111094
Low Stock     69425
Name: count, dtype: int64

In [ ]:
final_df.to_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Processed/Final_Inventory_Model.csv",
    index=False
)

In [ ]:
final_df["order_date"] = pd.to_datetime(
    final_df["order_date"],
    format="mixed",
    dayfirst=False
)

final_df["shipping_date"] = pd.to_datetime(
    final_df["shipping_date"],
    format="mixed",
    dayfirst=False
)

In [ ]:
final_df[["order_date", "shipping_date"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_date     180519 non-null  datetime64[ns]
 1   shipping_date  180519 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 2.8 MB

In [ ]:
final_df["order_date"].head(20)

0    2017-02-26 17:17:00
1    2015-02-27 00:47:00
2    2017-01-29 04:43:00
3    2015-01-18 04:42:00
4    2017-03-28 17:36:00
5    2017-06-05 15:34:00
6    2017-03-08 07:28:00
7    2017-06-05 15:34:00
8    2017-01-21 00:52:00
9    2015-02-11 16:35:00
10   2015-04-08 10:54:00
11   2017-02-07 10:50:00
12   2017-02-14 07:29:00
13   2015-04-24 02:28:00
14   2017-03-10 02:54:00
15   2017-01-26 05:14:00
16   2015-05-20 09:26:00
17   2015-02-11 16:35:00
18   2015-04-25 00:53:00
19   2015-02-27 00:47:00
Name: order_date, dtype: datetime64[ns]

In [ ]:
final_df["shipping_date"].head(20)

0    2017-03-02 17:17:00
1    2015-03-03 00:47:00
2    2017-02-03 04:43:00
3    2015-01-23 04:42:00
4    2017-04-02 17:36:00
5    2017-06-11 15:34:00
6    2017-03-14 07:28:00
7    2017-06-11 15:34:00
8    2017-01-27 00:52:00
9    2015-02-14 16:35:00
10   2015-04-11 10:54:00
11   2017-02-11 10:50:00
12   2017-02-18 07:29:00
13   2015-04-29 02:28:00
14   2017-03-15 02:54:00
15   2017-02-01 05:14:00
16   2015-05-26 09:26:00
17   2015-02-14 16:35:00
18   2015-04-29 00:53:00
19   2015-03-03 00:47:00
Name: shipping_date, dtype: datetime64[ns]

In [ ]:
final_df.to_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Processed/Final_Inventory_Model.csv",
    index=False
)