**Importing libraries and loading the dataset and checking the record present in dataset by using head function**

In [ ]:
import pandas as pd
inventory_df=pd.read_csv("/content/Inventory_Stock_Data.csv")
inventory_df.head(10)

,order-now,product id,product name,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
0,green,19,Nike Men's Fingertrap Max Training Shoe,10,1,69,30,1,1,35,25
1,orange,24,Elevation Training Mask 2.0,10,3,175,30,5,0,175,144
2,green,35,adidas Brazuca 2014 Official Match Ball,10,1,65,30,1,1,35,25
3,green,37,adidas Kids' F5 Messi FG Soccer Cleat,10,3,328,30,5,1,175,146
4,orange,44,adidas Men's F10 Messi TRX FG Soccer Cleat,10,3,175,30,5,0,175,145
5,orange,58,Diamondback Boys' Insight 24 Performance Hybr,10,1,35,30,1,0,35,25
6,orange,60,SOLE E25 Elliptical,10,1,35,30,1,0,35,25
7,green,61,Diamondback Girls' Clarity 24 Hybrid Bike 201,10,1,61,30,1,1,35,25
8,orange,78,Nike Kids' Grade School KD VI Basketball Shoe,10,3,175,30,5,0,175,146
9,green,93,Under Armour Men's Tech II T-Shirt,10,3,324,30,5,1,175,146

**Checking the rows and columns present in the dataset**

In [ ]:
inventory_df.shape

(118, 11)

In [ ]:
inventory_df.describe()

,product id,avg lead time,avg order qty,current stock,max lead time,max order qty,mod,reorder point,safety stock
count,118.000000,118.0,118.000000,118.000000,118.0,118.000000,118.000000,118.000000,118.000000
mean,689.576271,10.0,2.084746,160.720339,30.0,3.169492,0.542373,110.932203,90.330508
std,403.120380,0.0,1.000652,115.003819,0.0,2.001303,0.500326,70.045617,60.270055
min,19.000000,10.0,1.000000,35.000000,30.0,1.000000,0.000000,35.000000,25.000000
25%,303.500000,10.0,1.000000,63.000000,30.0,1.000000,0.000000,35.000000,25.000000
50%,729.000000,10.0,3.000000,175.000000,30.0,5.000000,1.000000,175.000000,144.000000
75%,905.750000,10.0,3.000000,321.000000,30.0,5.000000,1.000000,175.000000,146.000000
max,1363.000000,10.0,3.000000,330.000000,30.0,5.000000,1.000000,175.000000,148.000000

**Checking dataset information This shows:

Data types
Missing values
Total rows**

In [ ]:
inventory_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order-now      118 non-null    object
 1   product id     118 non-null    int64
 2   product name   118 non-null    object
 3   avg lead time  118 non-null    int64
 4   avg order qty  118 non-null    int64
 5   current stock  118 non-null    int64
 6   max lead time  118 non-null    int64
 7   max order qty  118 non-null    int64
 8   mod            118 non-null    int64
 9   reorder point  118 non-null    int64
 10  safety stock   118 non-null    int64
dtypes: int64(9), object(2)
memory usage: 10.3+ KB

**Checking column names present in dataset**

In [ ]:
inventory_df.columns

Index(['order-now', 'product id', 'product name', 'avg lead time',
       'avg order qty', 'current stock', 'max lead time', 'max order qty',
       'mod', 'reorder point', 'safety stock'],
      dtype='object')

**Removing Extra Spaces from columns names if present**

In [ ]:
inventory_df.columns=inventory_df.columns.str.strip()

**Checking if missing values are present in dataset or not**

In [ ]:
inventory_df.isnull().sum()

order-now        0
product id       0
product name     0
avg lead time    0
avg order qty    0
current stock    0
max lead time    0
max order qty    0
mod              0
reorder point    0
safety stock     0
dtype: int64

**Checking for duplicates values present in dataset**

In [ ]:
inventory_df.duplicated().sum()

np.int64(0)

**Checking duplicate products ids in dataset**

In [ ]:
inventory_df["product id"].duplicated().sum()

np.int64(0)

In [ ]:
inventory_df.columns
inventory_df.columns = [
    "order_now",
    "product_id",
    "product_name",
    "avg_lead_time",
    "avg_order_qty",
    "current_stock",
    "max_lead_time",
    "max_order_qty",
    "mod",
    "reorder_point",
    "safety_stock"
]

In [ ]:
inventory_df.describe()

,product_id,avg_lead_time,avg_order_qty,current_stock,max_lead_time,max_order_qty,mod,reorder_point,safety_stock
count,118.000000,118.0,118.000000,118.000000,118.0,118.000000,118.000000,118.000000,118.000000
mean,689.576271,10.0,2.084746,160.720339,30.0,3.169492,0.542373,110.932203,90.330508
std,403.120380,0.0,1.000652,115.003819,0.0,2.001303,0.500326,70.045617,60.270055
min,19.000000,10.0,1.000000,35.000000,30.0,1.000000,0.000000,35.000000,25.000000
25%,303.500000,10.0,1.000000,63.000000,30.0,1.000000,0.000000,35.000000,25.000000
50%,729.000000,10.0,3.000000,175.000000,30.0,5.000000,1.000000,175.000000,144.000000
75%,905.750000,10.0,3.000000,321.000000,30.0,5.000000,1.000000,175.000000,146.000000
max,1363.000000,10.0,3.000000,330.000000,30.0,5.000000,1.000000,175.000000,148.000000

In [ ]:
inventory_df.to_csv("Inventory_Cleaned.csv", index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'AdmitCard-220320031703 (1).pdf',
 'IMG-20221016-WA0008.jpg',
 'Adobe Scan Oct 17, 2022_1.pdf',
 '20221019_190946.jpg',
 '20221019_191020.jpg',
 '20221019_191208.jpg',
 '16661880190932484392156975096424.jpg',
 '16661884233958632130302657038588.jpg',
 '16661886128407602160809779581349.jpg',
 '20221019_194548.jpg',
 '16661893553916666004947933337767.jpg',
 '16661894265832469446121460086117.jpg',
 '16661934519727032188299563068566.jpg',
 '20240315_182742.jpg',
 'IMG-20240419-WA0003.jpg',
 'RESUME.docx',
 'SIMRANCHOUDHARY-India_Internship-certificate.pdf',
 'SIMRANCHOUDHARY-India_Internship-certificate (1) (1).pdf',
 'SIMRANCHOUDHARY-India_Internship-certificate (1) (5).pdf',
 'Problem Statement .pdf',
 'Untitled form.gform',
 'IMG-20241125-WA0005.jpg',
 'Dataset',
 'Untitled spreadsheet (3).gsheet',
 'GoogleDataAnalyticsProfessionalCertificate_Badge20250301-28-u553w5 (1).pdf',
 'Resume.gdoc',
 'GoogleDataAnalyticsProfessionalCertificate_Badge20250301-28-u553w5.pdf',
 'DOC-20250402-WA0002_ (3)_resumeda222.docx',
 '20250724_202702-min (1).jpg',
 'Screenshot_20250311-190638_Chrome.jpg',
 '20250724_202702-min.jpg',
 'Scanned_20250912-1100.pdf',
 'Scanned_20250912-1101.pdf',
 'Scanned_20250912-1103 (1).pdf',
 'Scanned_20250912-1103.pdf',
 'Scanned_20250912-1104.pdf',
 'Project',
 'simran_choudhary_resumecf_9_2025.pdf',
 'finance-dashboard-2026-01-31T13-07-16.747Z.pdf',
 'Illegal Migrants Data.XLSX',
 'Untitled spreadsheet (2).gsheet',
 'grapess.png',
 'images.jpg',
 'kite.png',
 'Untitled spreadsheet (1).gsheet',
 'Untitled spreadsheet.gsheet',
 'finance-dashboard-2026-04-25T17-26-04.317Z.pdf',
 'SIMRAN  CHOUDHARY 28-04-2026 (1).pdf',
 'Simran_Choudhary_24 June.pdf',
 'IMG-20250921-WA0031.jpg',
 'Simran_24 June.pdf',
 '20240301_181810.jpg',
 'Data comparison for ninl (1).xlsx',
 'Data comparison for ninl.xlsx',
 'Supply_Chain_Optimization_Project']

In [ ]:
inventory_df = pd.read_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Raw/Inventory_Stock_Data.csv"
)

In [ ]:
inventory_df.to_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Cleaned/Inventory_Cleaned.csv",
    index=False
)