In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
sales_df = pd.read_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Raw/Sales_Shipment_Data.csv"
)

In [ ]:
sales_df.head()

,Product Category Id,Category Name,Class,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,...,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Order Item Total,Order Profit Per Order,Product Price,Sales,Sales per customer
0,24,Women's Apparel,Moderate Value-Moderate Number,Roswell,EE. UU.,Jean,5673,Dunn,Corporate,NM,...,0.15,134920,50.0,0.11,2,85.0,9.610000,50.0,100.0,85.0
1,24,Women's Apparel,Moderate Value-Moderate Number,Los Angeles,EE. UU.,Rose,9723,White,Corporate,CA,...,0.16,9722,50.0,0.11,2,84.0,9.490000,50.0,100.0,84.0
2,24,Women's Apparel,Moderate Value-Moderate Number,Harvey,EE. UU.,Joshua,9511,Brady,Corporate,IL,...,0.06,129954,50.0,0.33,2,94.5,30.709999,50.0,100.0,94.5
3,24,Women's Apparel,Moderate Value-Moderate Number,Elmhurst,EE. UU.,Mary,3326,Smith,Corporate,IL,...,0.05,2929,50.0,0.29,2,95.0,27.549999,50.0,100.0,95.0
4,24,Women's Apparel,Moderate Value-Moderate Number,North Las Vegas,EE. UU.,Samantha,907,Kline,Corporate,NV,...,0.05,140056,50.0,0.50,2,95.0,47.500000,50.0,100.0,95.0

In [ ]:
sales_df.shape

(180519, 46)

In [ ]:
sales_df.columns

Index(['Product Category Id', 'Category Name', 'Class', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Delivery Status', 'Department Id',
       'Department Name', 'Market', 'Order City', 'Order Country',
       'order date (DateOrders)', 'Order Id', 'Order Region', 'Order State',
       'Order Status', 'Product Id', 'Product Name',
       'shipping date (DateOrders)', 'Shipping Mode', 'Type',
       'Benefit per order', 'Days for shipment (scheduled)',
       'Days for shipping (real)', 'Latitude', 'Longitude',
       'Order Customer Id', 'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Order Item Total',
       'Order Profit Per Order', 'Product Price', 'Sales',
       'Sales per customer'],
      dtype='object')

In [ ]:
sales_df.columns = sales_df.columns.str.strip()

In [ ]:
sales_df.columns

Index(['Product Category Id', 'Category Name', 'Class', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Delivery Status', 'Department Id',
       'Department Name', 'Market', 'Order City', 'Order Country',
       'order date (DateOrders)', 'Order Id', 'Order Region', 'Order State',
       'Order Status', 'Product Id', 'Product Name',
       'shipping date (DateOrders)', 'Shipping Mode', 'Type',
       'Benefit per order', 'Days for shipment (scheduled)',
       'Days for shipping (real)', 'Latitude', 'Longitude',
       'Order Customer Id', 'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Order Item Total',
       'Order Profit Per Order', 'Product Price', 'Sales',
       'Sales per customer'],
      dtype='object')

In [ ]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 46 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Product Category Id            180519 non-null  int64
 1   Category Name                  180519 non-null  object
 2   Class                          180519 non-null  object
 3   Customer City                  180519 non-null  object
 4   Customer Country               180519 non-null  object
 5   Customer Fname                 180519 non-null  object
 6   Customer Id                    180519 non-null  int64
 7   Customer Lname                 180511 non-null  object
 8   Customer Segment               180519 non-null  object
 9   Customer State                 180519 non-null  object
 10  Customer Street                180519 non-null  object
 11  Customer Zipcode               180516 non-null  float64
 12  Delivery Status                180519 non-null  object
 13  Department Id                  180519 non-null  int64
 14  Department Name                180519 non-null  object
 15  Market                         180519 non-null  object
 16  Order City                     180519 non-null  object
 17  Order Country                  180519 non-null  object
 18  order date (DateOrders)        180519 non-null  object
 19  Order Id                       180519 non-null  int64
 20  Order Region                   180519 non-null  object
 21  Order State                    180519 non-null  object
 22  Order Status                   180519 non-null  object
 23  Product Id                     180519 non-null  int64
 24  Product Name                   180519 non-null  object
 25  shipping date (DateOrders)     180519 non-null  object
 26  Shipping Mode                  180519 non-null  object
 27  Type                           180519 non-null  object
 28  Benefit per order              180519 non-null  float64
 29  Days for shipment (scheduled)  180519 non-null  int64
 30  Days for shipping (real)       180519 non-null  int64
 31  Latitude                       180519 non-null  float64
 32  Longitude                      180519 non-null  float64
 33  Order Customer Id              180519 non-null  int64
 34  Order Item Cardprod Id         180519 non-null  int64
 35  Order Item Discount            180519 non-null  float64
 36  Order Item Discount Rate       180519 non-null  float64
 37  Order Item Id                  180519 non-null  int64
 38  Order Item Product Price       180519 non-null  float64
 39  Order Item Profit Ratio        180519 non-null  float64
 40  Order Item Quantity            180519 non-null  int64
 41  Order Item Total               180519 non-null  float64
 42  Order Profit Per Order         180519 non-null  float64
 43  Product Price                  180519 non-null  float64
 44  Sales                          180519 non-null  float64
 45  Sales per customer             180519 non-null  float64
dtypes: float64(13), int64(11), object(22)
memory usage: 63.4+ MB

In [ ]:
sales_df.isnull().sum()

Product Category Id              0
Category Name                    0
Class                            0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   8
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Delivery Status                  0
Department Id                    0
Department Name                  0
Market                           0
Order City                       0
Order Country                    0
order date (DateOrders)          0
Order Id                         0
Order Region                     0
Order State                      0
Order Status                     0
Product Id                       0
Product Name                     0
shipping date (DateOrders)       0
Shipping Mode                    0
Type                             0
Benefit per order                0
Days for shipment (scheduled)    0
Days for shipping (real)         0
Latitude                         0
Longitude                        0
Order Customer Id                0
Order Item Cardprod Id           0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Id                    0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Order Item Total                 0
Order Profit Per Order           0
Product Price                    0
Sales                            0
Sales per customer               0
dtype: int64

In [ ]:
sales_df.duplicated().sum()

np.int64(0)

In [ ]:
required_columns = [
    "Product Id",
    "Product Name",
    "Category Name",
    "Department Name",
    "Order Id",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Delivery Status",
    "Shipping Mode",
    "Order Region",
    "Order Country",
    "Market",
    "Order Item Quantity",
    "Product Price",
    "Sales",
    "Benefit per order",
    "Order Profit Per Order",
    "Days for shipment (scheduled)",
    "Days for shipping (real)",
    "Order Status",
    "Customer Segment"
]

In [ ]:
sales_cleaned = sales_df[required_columns]

In [ ]:
sales_cleaned.head()

,Product Id,Product Name,Category Name,Department Name,Order Id,order date (DateOrders),shipping date (DateOrders),Delivery Status,Shipping Mode,Order Region,...,Market,Order Item Quantity,Product Price,Sales,Benefit per order,Order Profit Per Order,Days for shipment (scheduled),Days for shipping (real),Order Status,Customer Segment
0,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,53963,2/26/2017 17:17,03-02-2017 17:17,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,9.610000,9.610000,2,4,Pending Payment,Corporate
1,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,3908,2/27/2015 0:47,03-03-2015 00:47,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,9.490000,9.490000,2,4,Pending Payment,Corporate
2,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,52009,1/29/2017 4:43,02-03-2017 04:43,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,30.709999,30.709999,2,5,Payment Review,Corporate
3,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,1179,1/18/2015 4:42,1/23/2015 4:42,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,27.549999,27.549999,2,5,Pending Payment,Corporate
4,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,56019,3/28/2017 17:36,04-02-2017 17:36,Late,Second Class,Central America,...,LATAM,2,50.0,100.0,47.500000,47.500000,2,5,Pending Payment,Corporate

In [ ]:
sales_cleaned.shape

(180519, 21)

In [ ]:
sales_cleaned.columns = [
    "product_id",
    "product_name",
    "category_name",
    "department_name",
    "order_id",
    "order_date",
    "shipping_date",
    "delivery_status",
    "shipping_mode",
    "order_region",
    "order_country",
    "market",
    "order_quantity",
    "product_price",
    "sales",
    "benefit_per_order",
    "order_profit",
    "scheduled_shipping_days",
    "actual_shipping_days",
    "order_status",
    "customer_segment"
]

In [ ]:
sales_cleaned.columns

Index(['product_id', 'product_name', 'category_name', 'department_name',
       'order_id', 'order_date', 'shipping_date', 'delivery_status',
       'shipping_mode', 'order_region', 'order_country', 'market',
       'order_quantity', 'product_price', 'sales', 'benefit_per_order',
       'order_profit', 'scheduled_shipping_days', 'actual_shipping_days',
       'order_status', 'customer_segment'],
      dtype='object')

In [ ]:
sales_cleaned.to_csv(
    "/content/drive/MyDrive/Supply_Chain_Optimization_Project/Dataset/Cleaned/Sales_Cleaned.csv",
    index=False
)